# Generated by Django 2.1 on 2020-12-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date Of Payment')),
                ('member_id', models.CharField(max_length=10)),
                ('purpose', models.CharField(max_length=50, verbose_name='Purpose Of Payment')),
                ('bank', models.CharField(max_length=50, verbose_name='Bank')),
                ('transac_id', models.CharField(max_length=120, verbose_name='Transac. ID/Teller No.')),
                ('amount', models.CharField(max_length=120, verbose_name='Amount')),
                ('confirmed', models.CharField(choices=[('Yes', 'Approved'), ('No', 'Not Approved')], max_length=10, verbose_name='Confirmed?')),
                ('evidence_file', models.FileField(upload_to='evidence_files/')),
            ],
        ),
    ]
