# Generated by Django 2.1 on 2020-10-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('member_id', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('loan_type', models.CharField(max_length=120, verbose_name='Loan Type')),
                ('loan_amount', models.CharField(max_length=120, verbose_name='Loan Amount')),
                ('year_val', models.CharField(max_length=4, verbose_name='Year')),
                ('month', models.CharField(choices=[('JANUARY', 'JANUARY'), ('FEBRUARY', 'FEBRUARY'), ('MARCH', 'MARCH'), ('APRIL', 'APRIL'), ('MAY', 'MAY'), ('JUNE', 'JUNE'), ('JULY', 'JULY'), ('AUGUST', 'AUGUST'), ('SEPTEMBER', 'SEPTEMBER'), ('OCTOBER', 'OCTOBER'), ('NOVEMBER', 'NOVEMBER'), ('DECEMBER', 'DECEMBER')], max_length=15)),
                ('loan_status', models.CharField(choices=[('Yes', 'Approved'), ('No', 'Not Approved')], max_length=10, verbose_name='Approved?')),
            ],
        ),
        migrations.CreateModel(
            name='LoanSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=120, verbose_name='Loan Type')),
                ('percentage_val', models.CharField(max_length=10)),
                ('year_val', models.CharField(max_length=4, verbose_name='Year')),
                ('month', models.CharField(choices=[('JANUARY', 'JANUARY'), ('FEBRUARY', 'FEBRUARY'), ('MARCH', 'MARCH'), ('APRIL', 'APRIL'), ('MAY', 'MAY'), ('JUNE', 'JUNE'), ('JULY', 'JULY'), ('AUGUST', 'AUGUST'), ('SEPTEMBER', 'SEPTEMBER'), ('OCTOBER', 'OCTOBER'), ('NOVEMBER', 'NOVEMBER'), ('DECEMBER', 'DECEMBER')], max_length=50)),
                ('max_loan_amnt', models.CharField(max_length=120, verbose_name='Max Loan Amount Available')),
            ],
        ),
    ]
