# Generated by Django 2.1 on 2020-10-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20201015_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansetting',
            name='loan_type',
            field=models.CharField(max_length=120, verbose_name='Loan Type'),
        ),
    ]
