# Generated by Django 2.1 on 2020-12-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20201204_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
